### ISSUE TITLE
Handling open PRs from SF

### ISSUE THREAD

**Issue by hhoffstaette** [joe-editor/joe#7]
I'm glad to see joe here on GH but it's not clear (to me) whether this is supposed to be the new official home repo or some other effort. Primarily I'm curious if there are any plans to incorporate the open PRs on SF; I help maintain joe on Gentoo and we cooperate a lot with Fedora, so having those fixes upstreamed here would be useful moving forward.
Could you clarify?

**Comment by jjjordan** [comment]
It's been a while since I spoke with @jhallen on this. iirc the plan moving forward is to have primary development occur in this repo and keep the SF project page around for releases and issues, since there are still decades of links pointing there.

The Mercurial repo is deprecated - vanishingly few services/hosts support it anymore, but we can still absolutely sync things from there in the short term before this diverges too much. I admit I hadn't realized the open PR's over there. Perhaps we should make an effort to merge those into Mercurial, then I can port them back across before we close it down.

I might try to set up mirroring back to a new Git repo over there for some kind of parity, but I haven't planned that far out yet.

But perhaps Joe wants to chime in.

**Comment by jjjordan** [comment]
I've merged 2 of the 3 in #9. The last one needs further review.

**Comment by hhoffstaette** [comment]
Thank you very much for explaining the situation and merging proactively!
